### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SamCrep** [MrSonicMaster/vHackXT-MoneyBot#18]
module.js:487
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Sebastiano\Desktop\vHackXT-MoneyBot-master\methods.js:11:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
Can you help me pls.

**Comment by MrSonicMaster** [comment]
Please read the section for 'Installation.' This states how to install all the required libraries in order to get this script working, but please note this is a bit outdated, I haven't updated it to work with the latest version of vHack yet (my account got banned, lost motivation to continue this project.)

**Comment by MrSonicMaster** [comment]
Re-open it if you still have an issue, but for now I'll close it.
