### ISSUE TITLE
Startup issue 

### ISSUE THREAD

**Issue by ghost** [MrSonicMaster/vHackXT-MoneyBot#2]
# Issue

Bot doesn't start because of following issue:

```
$:~/workdir/vHackXT-MoneyBot$ ./StartBot_Linux.sh 
/home/foobar/workdir/vHackXT-MoneyBot/vHack.js:137
	log(message, logLevel = 0) {
	                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

```

node --version v4.7.2
Linux 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux

**Comment by ghost** [comment]
This change in your vhack.js fix this issue for me:

```
// YOUR STUFF
//  log(message, logLevel = 0) {
//      if (this.debugLevel >= logLevel) console.log(`Client ${this.clientID}: ${message}`);
//  }
// MY STUFF
    log(message) {
        console.log(`Client ${this.clientID}: ${message}`);
    }
}

```

**Comment by MrSonicMaster** [comment]
Once again, this issue is because you used an outdated version of NODE that doesn't support ES6 syntax. I suggest you use this article to help you install the latest version of NODE on your linux operating system: https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
