### ISSUE TITLE
Client 0: Fatal error: Status code is 500 for vh_loadRemoteData.php.

### ISSUE THREAD

**Issue by ghost** [MrSonicMaster/vHackXT-MoneyBot#4]
HI,

i often got the issue:
Client 0: Fatal error: Status code is 500 for vh_loadRemoteData.php.

Bot is working properly and earned money, but sometimes this error occures:

Client 0: Get new player list.
Client 0: Get new player list.
Client 0: Get new player list.
Client 0: Fatal error: Status code is 500 for vh_loadRemoteData.php.
Client 0: Get new player list.
Client 0: Get new player list.
Client 0: Fatal error: Status code is 500 for vh_loadRemoteData.php.
Client 0: Get new player list.
Client 0: Get new player list.
Client 0: Get new player list.
Client 0: Get new player list.

Any idea to fix this? Did you need more info (debug mode 4)?

king greetz

**Comment by MrSonicMaster** [comment]
A status code of 500 indicates an error server-sided, it is an error with vHack XT's own PHP code, this would need to be reported to them (unless I made an error in my code and send wrong data, but it doesn't seem that way because all the other times it works fine.) It might be another issue, like the "Status code is 404..." error, meaning that you have sent too many requests in too short of time, but that is also unlikely because it doesn't seem to occur in the same conditions as the 404 status code. I'll leave the issue open until it no longer happens (they fixed it server-sided) or I find an error in my code.

**Comment by someonewhoplayvhack** [comment]
ye some of my freinds have this error too

**Comment by YourSelft487** [comment]
Same Here, I got some:
Client 0: Get new player list.
but mostly I get this error:
Client 0: Fatal error: Status code is 500 for vh_loadRemoteData.php.

Looks like this is server-side problem with script.
maybe too many connection at one time (I will try anothertime)

Hope this will be fix by VhTeam :p

**Comment by MrSonicMaster** [comment]
Yeah

**Comment by MrSonicMaster** [comment]
Successfully reproduced where it spams this error instead of preforming like it should, I will look for a fix ASAP.

**Comment by MrSonicMaster** [comment]
I think I know what might be causing this, the server-sided script is storing some information server-sided, and something in my bot is overlapping with this causing their server-sided script to not know what to do. I will look further into it when I have time.

**Comment by Tsm020** [comment]
Any update if this is gonna be fixed?
Tsm020

**Comment by SamCrep** [comment]
Client 0: Starting login...
C:\Windows\system32\node_modules\md5\md5.js:152
      throw new Error('Illegal argument ' + message);
      ^

Error: Illegal argument undefined
    at module.exports (C:\Windows\system32\node_modules\md5\md5.js:152:13)
    at Methods.getEndURL (C:\Windows\system32\methods.js:34:41)
    at Methods.getUserInfo (C:\Windows\system32\methods.js:48:16)
    at vHackBot.login (C:\Windows\system32\vHack.js:25:11)
    at new vHackBot (C:\Windows\system32\vHack.js:20:8)
    at Object.<anonymous> (C:\Windows\system32\vHack.js:113:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

Help me pls I run as admin but doesn't work
